language: node_js
node_js:
- '6'
- node
sudo: required
services:
- docker
before_install:
- npm link
- npm install -g npm@'>=2.13.5'
- docker pull rabbitmq:3-management
- docker run -d -p 5671:5671 -p 15672:15672 -p 5672:5672 rabbitmq:3-management
script: npm run build-test
notifications:
  slack:
    secure: Qk4sUUQSQ/hFlANo40SC0S4fOvEIdJ2wBEzOm17QzyPFBLPzcGorFJcNVaJcBQ18qWn64RMi2ona+00PtTSOUBb/xNeHLvE/NC4Qyu0SDHNmsNV/0DJ7ODJlqAHL1OVjfhMDsngLKSJSTmudeXPTCFrNGh4yeNX9qkfnobK/xhJxSpCPVdR6wHHmgjwEQ5WDQGGGpvYKBCrD8a0+ko2/WOjdjFUVBEEAqdBVBdF9E4zFn6A1Mp5baxy3SNzfTuSS/usxq5Ayd6qnYITv7CvxqCsH/4mGyrWgTD0OJCXamDWGJFM1dbhOsGN4rT3w6fcwErObjEJwjPT1bnNZyMvafUgYufroE2dMhl13vziTWbZ4cYHpc1FHbcuKCeHJKNWZQMSe70xf5DZINUHB0yug25OqOIQrFglzlWSdz7ro0XCmBSa88U5aVjWLXeX8ZV7PjuteQmJ0PI8/ROKA/XNyji96lScSteuY+sURgh/8CASXDL/7+YEiJO8HzN85XlbDwPuNQWApBhyW04DQbe8P7TjCv/y9lvGZ71RqaSDmYXs/dd3jh+JK3m3+wY1lt6DpTXUWdOuFQEJwV3QkTBG0Gb1aI+86IVRisAvkSa1+hC9xSEs44volv00pWemaAsiG4HnQha/lKh6e8kwIy2ac1SE1oKzVrTCoPMrWIhjuClo=
deploy:
  provider: npm
  email: xo-npmjs.group@xogrp.com
  api_key:
    secure: XITIvxagH3v5rusG8nrWb88H7rqZsgUtzWOJ1pUakBgNaBiddCzb7BC3/m3WDdeelTn2R52K8gOEzbUnukzwiFw52Ymp2iUGqz3E/tb9GH3XusdzJVIJhJgFxOMt1s3QbUfPpZH7W/eSCGqEJ5Y1ZeapYFg8CoPewKVYp6eCipqWIuTUf+zhLSnlca4q+vnl6P7bH35H440GJondiHXSJ65ShMpBrV0wFDT6Jn5VzzFtY6Y++EYmUeClUL2ItQz7Cb6Zilke/aZkGTRuA1xnJwThue2Fc1XIN3hAAQt2+hEz/8WNwfP5l+w310bWjkHry2CVHzsl508TYRrcX1pdR+BQZv6pDxjRoeNAny3nAqJxAMR1K5dQ5C1xB/1BhlANOaFHvj8sWyLEbtPEZ7qMQces8lZoBdLVGw03qmrP2ErbqQSAgSc8WCHRDwJmf8rH33DcDF2FWgyV+liGmSF5xTB9ePQj+lQYa8AOe7hPCTcn/TiZ0eqOTYO6HM1Emgc75/BhsOUy08pqaLqm/5Nl4NKjUUyhv028/HKfpqqOHQ40xCvPVmam+cefGEOdC4dWe9oomeNlQNz4WMDspvG0Veaivg3BjoRax1lfeU/0TnZAKkZjD9//mfgf4kFzVW22p1gN4+45Y0goolYE7jUA5vaXMCj0dd5/RPFp4fmBXhM=
  on:
    tags: true
    repo: xogroup/bunnybus-cli
