language: node_js
node_js:
- '6'
- node
sudo: required
services:
- docker
before_install:
- npm install -g npm@'>=2.13.5'
- docker pull rabbitmq:3-management
- docker run -d -p 5671:5671 -p 15672:15672 -p 5672:5672 rabbitmq:3-management
script: npm run build-test
