language: node_js
node_js:
- '6'
- node
sudo: required
services:
- docker
before_install:
- npm install -g npm@'>=2.13.5'
- docker pull rabbitmq:3-management
- docker run -d -p 5671:5671 -p 15672:15672 -p 5672:5672 rabbitmq:3-management
script: npm run build-test
deploy:
  provider: npm
  email: xo-npmjs.group@xogrp.com
  api_key:
    secure: CFnL0AcFCoELeuAraMeGSx15J0jty8xNbgyyWcvTIwNKOKQDs105Smkd8UeK3gPP6vHCfZdBbnm81Ymr0cnSCHpEhW+vRmkMj1tYYvVdq04feHOTo1tUb8Y05Ocbzn0h8ucF6Lu8sycFhCaxvoOzx5Hq50+URIS9JgFRyE1VIcvlCl8Mx7NzTnq/rVnONOHbGZto8spsKYRsXc6KsNG0HuKsNjyw5dQU9Baq5kiW//IrrFycej0x48QAHieV+5lVRAufORmiIVJUbjlX/tFkoggQO/k97jeKys9w/zbkqjoueYkC8byTYZ0tybnyXWpgOYTw5zY+J0lNCUa9qr/wUHZ2R98dWJwXMa4dRZLdblqDfK1IaT8zz9DgT4I6+ca7DrJzpd73wTukVhce9YKC7QKMsnwv8xr2SUhReVcVnzd5EafDEMetxV/NM3geMMeHnzpI6Z+jK29rxS9kQrx1PwnlL55rMsG89Q2IxTIl6ILpLuOTQh5WZqSC9cCn3+5hnhWcfaulZ+QDVlw97xdjXQ+GDfx9DkOHZdcajioLe/vsT05y5p8wI8kCH7PoXnye2xUWnmgpBCDTfuDsC6PvhkbPUq4paIXC8flLQkjsQ9DAN65LeJY1e/EuLmCtoZMOJmc7WNpVgaOq/qQiqyapyCRuU02OnVp4RW2RdMMFjdU=
  on:
    tags: true
    repo: xogroup/bunnybus-cli
notifications:
  slack:
    secure: Qk4sUUQSQ/hFlANo40SC0S4fOvEIdJ2wBEzOm17QzyPFBLPzcGorFJcNVaJcBQ18qWn64RMi2ona+00PtTSOUBb/xNeHLvE/NC4Qyu0SDHNmsNV/0DJ7ODJlqAHL1OVjfhMDsngLKSJSTmudeXPTCFrNGh4yeNX9qkfnobK/xhJxSpCPVdR6wHHmgjwEQ5WDQGGGpvYKBCrD8a0+ko2/WOjdjFUVBEEAqdBVBdF9E4zFn6A1Mp5baxy3SNzfTuSS/usxq5Ayd6qnYITv7CvxqCsH/4mGyrWgTD0OJCXamDWGJFM1dbhOsGN4rT3w6fcwErObjEJwjPT1bnNZyMvafUgYufroE2dMhl13vziTWbZ4cYHpc1FHbcuKCeHJKNWZQMSe70xf5DZINUHB0yug25OqOIQrFglzlWSdz7ro0XCmBSa88U5aVjWLXeX8ZV7PjuteQmJ0PI8/ROKA/XNyji96lScSteuY+sURgh/8CASXDL/7+YEiJO8HzN85XlbDwPuNQWApBhyW04DQbe8P7TjCv/y9lvGZ71RqaSDmYXs/dd3jh+JK3m3+wY1lt6DpTXUWdOuFQEJwV3QkTBG0Gb1aI+86IVRisAvkSa1+hC9xSEs44volv00pWemaAsiG4HnQha/lKh6e8kwIy2ac1SE1oKzVrTCoPMrWIhjuClo=
